### ISSUE TITLE
Quick Question: WordNet to MongoDB

### ISSUE THREAD

**Issue by sammerry** [kapilreddy/Shabda-Sangraha#1]
What tool did you use migrate WordNet to MongoDB? Did you write your own or is there one publicly available?

**Comment by kapilreddy** [comment]
I think I wrote something that transforms WordNet data to something MongoDB can accept. I am not sure myself though it was a long time ago.

**Comment by pcorey** [comment]
Whatever you did, thanks! This is an awesome resource.
